### ISSUE TITLE
inertial damping excites the 85mHz oscillation?

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMX#10]
## Background
- When the inertial damping loops were closed in IP-L/T/Y, one peaky structure at ~ 85mHz appeared.
- This seemed to be either **_instability due to blending_** or **_exciting 2nd Yaw mode_**.

## What has done
- changed the cross-over frequency.
  - We seemed to find that frequency at the peaky structure followed the cross-over frequency.
- The IP-stage looked stable 
  - in terms of what?

## todo for sanity check
- check/compare the spectra to know if the peak caused mainly by blending or inertial damping
  - [ ] w/o blending, w/o inertial damping
  - [ ] w/ blending, w/o inertial damping
  - [ ] w/ blinding, w/ inertial damping
