### ISSUE TITLE
80mHz-Yaw is annoying 

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMX#15]
### Background
- 80 mHz Yaw peak was observed and not damped well.

### Todo
- [ ] check the coherence
- [ ] shape the filters ...

**Comment by YoshinoriFujii** [comment]
> check the coherence

- BF-Y signal had high coherence at the 80 mHz:

![spectra_ITMX_190531](https://user-images.githubusercontent.com/37787512/58675897-4608f700-8391-11e9-8964-8476d10ca753.png)

**Comment by YoshinoriFujii** [comment]
After offloading the Yaw and implementing only AC for BF-Yaw:

![spectra_ITMX_wBF-AC-1](https://user-images.githubusercontent.com/37787512/58676406-24a90a80-8393-11e9-9010-62db62b81397.png)

**Comment by YoshinoriFujii** [comment]
### at the filter of BF-Y:
- If AC * (-1) * dampSB * notch 3 is applied with gain of 0.5, The 80mHz mode was damped relatively efficiently.

![spectra_ITMX_wBF-AC-2](https://user-images.githubusercontent.com/37787512/58677016-57ec9900-8395-11e9-922d-676590d55b8b.png)

**Comment by YoshinoriFujii** [comment]
Todo
- [ ] measure the TF of BF-Y with IP is in the inertial-damped state.

**Comment by YoshinoriFujii** [comment]
From https://github.com/YoshinoriFujii/Weekly-task/issues/17,
It looked that the IP-inertial damping injected larger noise and this seemed to cause the amplification of 80 mHz peak.

Todo
- [ ] check what happens when the INT is closed at BF-Yaw.

**Comment by YoshinoriFujii** [comment]
### Filter designing

- mechanical TF
![Screenshot from 2019-06-04 17:31:35](https://user-images.githubusercontent.com/37787512/58863886-a92abe80-86ee-11e9-9e17-2a3e9de5875f.png)

- filter to be tested.
![Screenshot from 2019-06-04 17:36:13](https://user-images.githubusercontent.com/37787512/58864234-4b4aa680-86ef-11e9-9077-717a38a692b6.png)

- OLTF
![Screenshot from 2019-06-04 17:37:48](https://user-images.githubusercontent.com/37787512/58864370-851bad00-86ef-11e9-9a4a-e7fe62c6d056.png)

**Comment by YoshinoriFujii** [comment]
### 2019.6.5
- OLTF
![Screenshot from 2019-06-05 14:03:24](https://user-images.githubusercontent.com/37787512/58931475-c9b05280-879a-11e9-8244-fc269fae32f3.png)

- OLTF measured

![Screenshot from 2019-06-05 14:04:48](https://user-images.githubusercontent.com/37787512/58931529-f2d0e300-879a-11e9-894a-3a6fc23c861d.png)

- spectra was not so improved. =>?

**Comment by YoshinoriFujii** [comment]
FYI, see `/users/VISsvn/TypeAtower/ITMX/Measurements/20190605/OLTFmodel/`
