### ISSUE TITLE
sensor matrix diagonalization

### ISSUE THREAD

**Issue by gw-vis** [gw-vis/ITMX#2]
### TODO
- [ ] 1. check the actual positions of the sensors
- [ ] 2. update the matrices according to the above
- [ ] 3. see the resonance peak and measure the coupling ratio.

### Check points
- [ ] compare the methods 2. and 3.
