### ISSUE TITLE
actuator matrix diagonalization at IP

### ISSUE THREAD

**Issue by gw-vis** [gw-vis/ITMX#4]
### TODO
- [ ] 1. diagonalize by injecting a line at 3Hz
- [ ] 2. diagonalize by looking at the transfer functions and then watch the amplitude at 10 or 30 mHz.

### Check points
- [ ] confirm which method would be better 1. or 2.
